<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\YfmCompanion.Engine\YfmCompanion.Engine.csproj" />
    <ProjectReference Include="..\..\src\YfmCompanion.RetroArch\YfmCompanion.RetroArch.csproj" />
  </ItemGroup>
</Project>
