using System.Windows;
using System.Windows.Controls;

namespace YfmCompanion.Desktop;

public partial class MainWindow
{
    // Preserve the workflow's control contract while each tab owns its XAML namescope.
    private void RegisterTabControls()
    {
        RegisterName("OptimizerSourcePane", OwnedOptimizerPaneView.FindName("OptimizerSourcePane"));
        RegisterName("OptimizerSourceTitle", OwnedOptimizerPaneView.FindName("OptimizerSourceTitle"));
        RegisterName("OptimizerSourceSummary", OwnedOptimizerPaneView.FindName("OptimizerSourceSummary"));
        RegisterName("OptimizerStrategyPane", OwnedOptimizerPaneView.FindName("OptimizerStrategyPane"));
        RegisterName("CampaignScopeCombo", OwnedOptimizerPaneView.FindName("CampaignScopeCombo"));
        RegisterName("CampaignOpponentCombo", OwnedOptimizerPaneView.FindName("CampaignOpponentCombo"));
        RegisterName("CampaignOpponentHint", OwnedOptimizerPaneView.FindName("CampaignOpponentHint"));
        RegisterName("UseSavedStarChipsCheckBox", OwnedOptimizerPaneView.FindName("UseSavedStarChipsCheckBox"));
        RegisterName("CampaignInputHint", OwnedOptimizerPaneView.FindName("CampaignInputHint"));
        RegisterName("OptimizerProfileCombo", OwnedOptimizerPaneView.FindName("OptimizerProfileCombo"));
        RegisterName("PreferredTypesTextBox", OwnedOptimizerPaneView.FindName("PreferredTypesTextBox"));
        RegisterName("PreferredFieldCombo", OwnedOptimizerPaneView.FindName("PreferredFieldCombo"));
        RegisterName("OpponentTypesTextBox", OwnedOptimizerPaneView.FindName("OpponentTypesTextBox"));
        RegisterName("OptimizerProfileDescription", OwnedOptimizerPaneView.FindName("OptimizerProfileDescription"));
        RegisterName("OptimizerIncludeGlitchesCheckBox", OwnedOptimizerPaneView.FindName("OptimizerIncludeGlitchesCheckBox"));
        RegisterName("AlreadyRedeemedCardsTextBox", OwnedOptimizerPaneView.FindName("AlreadyRedeemedCardsTextBox"));
        RegisterName("OptimizerSpeedCombo", OwnedOptimizerPaneView.FindName("OptimizerSpeedCombo"));
        RegisterName("OptimizationStageText", OwnedOptimizerPaneView.FindName("OptimizationStageText"));
        RegisterName("OptimizationProgressBar", OwnedOptimizerPaneView.FindName("OptimizationProgressBar"));
        RegisterName("OptimizationProgressDetail", OwnedOptimizerPaneView.FindName("OptimizationProgressDetail"));
        RegisterName("ProveOptimalCheckBox", OwnedOptimizerPaneView.FindName("ProveOptimalCheckBox"));
        RegisterName("NewProofCheckpointCheckBox", OwnedOptimizerPaneView.FindName("NewProofCheckpointCheckBox"));
        RegisterName("OptimizeDeckButton", OwnedOptimizerPaneView.FindName("OptimizeDeckButton"));
        RegisterName("PauseOptimizationButton", OwnedOptimizerPaneView.FindName("PauseOptimizationButton"));
        RegisterName("StopOptimizationButton", OwnedOptimizerPaneView.FindName("StopOptimizationButton"));
        RegisterName("VerifyOptimizationButton", OwnedOptimizerPaneView.FindName("VerifyOptimizationButton"));
        RegisterName("OptimizationStatus", OwnedOptimizerPaneView.FindName("OptimizationStatus"));
        RegisterName("OptimizerBody", OwnedOptimizerPaneView.FindName("OptimizerBody"));
        RegisterName("OptimizerOwnedRow", OwnedOptimizerPaneView.FindName("OptimizerOwnedRow"));
        RegisterName("OptimizerResultRow", OwnedOptimizerPaneView.FindName("OptimizerResultRow"));
        RegisterName("OptimizerOwnedColumn", OwnedOptimizerPaneView.FindName("OptimizerOwnedColumn"));
        RegisterName("OptimizerResultColumn", OwnedOptimizerPaneView.FindName("OptimizerResultColumn"));
        RegisterName("OptimizerOwnedPane", OwnedOptimizerPaneView.FindName("OptimizerOwnedPane"));
        RegisterName("OwnedSearchBox", OwnedOptimizerPaneView.FindName("OwnedSearchBox"));
        RegisterName("OwnedTypeFilterCombo", OwnedOptimizerPaneView.FindName("OwnedTypeFilterCombo"));
        RegisterName("OwnedSortCombo", OwnedOptimizerPaneView.FindName("OwnedSortCombo"));
        RegisterName("OwnedAddPickerPanel", OwnedOptimizerPaneView.FindName("OwnedAddPickerPanel"));
        RegisterName("OwnedCollectionCount", OwnedOptimizerPaneView.FindName("OwnedCollectionCount"));
        RegisterName("OwnedCardsGallery", OwnedOptimizerPaneView.FindName("OwnedCardsGallery"));
        RegisterName("OptimizerResultPane", OwnedOptimizerPaneView.FindName("OptimizerResultPane"));
        RegisterName("Optimizer2800Metric", OwnedOptimizerPaneView.FindName("Optimizer2800Metric"));
        RegisterName("Optimizer2500Metric", OwnedOptimizerPaneView.FindName("Optimizer2500Metric"));
        RegisterName("OptimizerExpectedMetric", OwnedOptimizerPaneView.FindName("OptimizerExpectedMetric"));
        RegisterName("OptimizerDeadMetric", OwnedOptimizerPaneView.FindName("OptimizerDeadMetric"));
        RegisterName("CampaignPlanPanel", OwnedOptimizerPaneView.FindName("CampaignPlanPanel"));
        RegisterName("CampaignScopeSummary", OwnedOptimizerPaneView.FindName("CampaignScopeSummary"));
        RegisterName("CampaignSafetySummary", OwnedOptimizerPaneView.FindName("CampaignSafetySummary"));
        RegisterName("CampaignPurchaseSummary", OwnedOptimizerPaneView.FindName("CampaignPurchaseSummary"));
        RegisterName("OptimizedDeckGrid", OwnedOptimizerPaneView.FindName("OptimizedDeckGrid"));
        RegisterName("OptimizationTargetsGrid", OwnedOptimizerPaneView.FindName("OptimizationTargetsGrid"));
        RegisterName("LimitedCardsGrid", OwnedOptimizerPaneView.FindName("LimitedCardsGrid"));
        RegisterName("ExcludedCardsGrid", OwnedOptimizerPaneView.FindName("ExcludedCardsGrid"));
        RegisterName("PurchasePlanGrid", OwnedOptimizerPaneView.FindName("PurchasePlanGrid"));
        RegisterName("CampaignThreatsGrid", OwnedOptimizerPaneView.FindName("CampaignThreatsGrid"));
        RegisterName("RefreshSaveButton", SaveSnapshotPaneView.FindName("RefreshSaveButton"));
        RegisterName("ApplyDeckButton", SaveSnapshotPaneView.FindName("ApplyDeckButton"));
        RegisterName("ApplyOwnedButton", SaveSnapshotPaneView.FindName("ApplyOwnedButton"));
        RegisterName("SaveSnapshotStatus", SaveSnapshotPaneView.FindName("SaveSnapshotStatus"));
        RegisterName("SaveSourceText", SaveSnapshotPaneView.FindName("SaveSourceText"));
        RegisterName("SaveTimestampText", SaveSnapshotPaneView.FindName("SaveTimestampText"));
        RegisterName("SavePathText", SaveSnapshotPaneView.FindName("SavePathText"));
        RegisterName("SaveValidationText", SaveSnapshotPaneView.FindName("SaveValidationText"));
        RegisterName("SaveDeckGrid", SaveSnapshotPaneView.FindName("SaveDeckGrid"));
        RegisterName("SaveCollectionGrid", SaveSnapshotPaneView.FindName("SaveCollectionGrid"));
        RegisterName("LiveStatusText", LiveDuelPaneView.FindName("LiveStatusText"));
        RegisterName("InspectorToggleButton", LiveDuelPaneView.FindName("InspectorToggleButton"));
        RegisterName("LiveConnectionText", LiveDuelPaneView.FindName("LiveConnectionText"));
        RegisterName("LivePlayerLpText", LiveDuelPaneView.FindName("LivePlayerLpText"));
        RegisterName("LiveOpponentLpText", LiveDuelPaneView.FindName("LiveOpponentLpText"));
        RegisterName("LiveTerrainText", LiveDuelPaneView.FindName("LiveTerrainText"));
        RegisterName("LiveUpdateHealthText", LiveDuelPaneView.FindName("LiveUpdateHealthText"));
        RegisterName("LiveHandGrid", LiveDuelPaneView.FindName("LiveHandGrid"));
        RegisterName("LivePlayerFieldGrid", LiveDuelPaneView.FindName("LivePlayerFieldGrid"));
        RegisterName("LivePlayerSpellTrapGrid", LiveDuelPaneView.FindName("LivePlayerSpellTrapGrid"));
        RegisterName("LiveOpponentFieldGrid", LiveDuelPaneView.FindName("LiveOpponentFieldGrid"));
        RegisterName("LiveAdviceSummary", LiveDuelPaneView.FindName("LiveAdviceSummary"));
        RegisterName("LiveAdviceGrid", LiveDuelPaneView.FindName("LiveAdviceGrid"));
        RegisterName("LiveDeckGrid", LiveDuelPaneView.FindName("LiveDeckGrid"));
        RegisterName("LiveCollectionGrid", LiveDuelPaneView.FindName("LiveCollectionGrid"));
        RegisterName("DeckPickerPanel", DeckAnalyzerPaneView.FindName("DeckPickerPanel"));
        RegisterName("AnalyzeDeckButton", DeckAnalyzerPaneView.FindName("AnalyzeDeckButton"));
        RegisterName("LoadCurrentDeckButton", DeckAnalyzerPaneView.FindName("LoadCurrentDeckButton"));
        RegisterName("CancelDeckButton", DeckAnalyzerPaneView.FindName("CancelDeckButton"));
        RegisterName("DeckIncludeGlitchesCheckBox", DeckAnalyzerPaneView.FindName("DeckIncludeGlitchesCheckBox"));
        RegisterName("AnyFusionMetric", DeckAnalyzerPaneView.FindName("AnyFusionMetric"));
        RegisterName("AtLeast2500Metric", DeckAnalyzerPaneView.FindName("AtLeast2500Metric"));
        RegisterName("AtLeast2800Metric", DeckAnalyzerPaneView.FindName("AtLeast2800Metric"));
        RegisterName("AtLeast3000Metric", DeckAnalyzerPaneView.FindName("AtLeast3000Metric"));
        RegisterName("ExpectedAttackMetric", DeckAnalyzerPaneView.FindName("ExpectedAttackMetric"));
        RegisterName("DeadHandMetric", DeckAnalyzerPaneView.FindName("DeadHandMetric"));
        RegisterName("DeckResultSummary", DeckAnalyzerPaneView.FindName("DeckResultSummary"));
        RegisterName("DeckAnalysisProgressBar", DeckAnalyzerPaneView.FindName("DeckAnalysisProgressBar"));
        RegisterName("DeckResultsGrid", DeckAnalyzerPaneView.FindName("DeckResultsGrid"));
        RegisterName("HandPickerPanel", TurnAdviserPaneView.FindName("HandPickerPanel"));
        RegisterName("MonsterPickerPanel", TurnAdviserPaneView.FindName("MonsterPickerPanel"));
        RegisterName("SpellPickerPanel", TurnAdviserPaneView.FindName("SpellPickerPanel"));
        RegisterName("IncludeGlitchesCheckBox", TurnAdviserPaneView.FindName("IncludeGlitchesCheckBox"));
        RegisterName("TurnResultSummary", TurnAdviserPaneView.FindName("TurnResultSummary"));
        RegisterName("TurnResultsGrid", TurnAdviserPaneView.FindName("TurnResultsGrid"));
    }
    private Border OptimizerSourcePane => (Border)OwnedOptimizerPaneView.FindName("OptimizerSourcePane");
    private TextBlock OptimizerSourceTitle => (TextBlock)OwnedOptimizerPaneView.FindName("OptimizerSourceTitle");
    private TextBlock OptimizerSourceSummary => (TextBlock)OwnedOptimizerPaneView.FindName("OptimizerSourceSummary");
    private GroupBox OptimizerStrategyPane => (GroupBox)OwnedOptimizerPaneView.FindName("OptimizerStrategyPane");
    private ComboBox CampaignScopeCombo => (ComboBox)OwnedOptimizerPaneView.FindName("CampaignScopeCombo");
    private ComboBox CampaignOpponentCombo => (ComboBox)OwnedOptimizerPaneView.FindName("CampaignOpponentCombo");
    private TextBlock CampaignOpponentHint => (TextBlock)OwnedOptimizerPaneView.FindName("CampaignOpponentHint");
    private CheckBox UseSavedStarChipsCheckBox => (CheckBox)OwnedOptimizerPaneView.FindName("UseSavedStarChipsCheckBox");
    private TextBlock CampaignInputHint => (TextBlock)OwnedOptimizerPaneView.FindName("CampaignInputHint");
    private ComboBox OptimizerProfileCombo => (ComboBox)OwnedOptimizerPaneView.FindName("OptimizerProfileCombo");
    private TextBox PreferredTypesTextBox => (TextBox)OwnedOptimizerPaneView.FindName("PreferredTypesTextBox");
    private ComboBox PreferredFieldCombo => (ComboBox)OwnedOptimizerPaneView.FindName("PreferredFieldCombo");
    private TextBox OpponentTypesTextBox => (TextBox)OwnedOptimizerPaneView.FindName("OpponentTypesTextBox");
    private TextBlock OptimizerProfileDescription => (TextBlock)OwnedOptimizerPaneView.FindName("OptimizerProfileDescription");
    private CheckBox OptimizerIncludeGlitchesCheckBox => (CheckBox)OwnedOptimizerPaneView.FindName("OptimizerIncludeGlitchesCheckBox");
    private TextBox AlreadyRedeemedCardsTextBox => (TextBox)OwnedOptimizerPaneView.FindName("AlreadyRedeemedCardsTextBox");
    private ComboBox OptimizerSpeedCombo => (ComboBox)OwnedOptimizerPaneView.FindName("OptimizerSpeedCombo");
    private TextBlock OptimizationStageText => (TextBlock)OwnedOptimizerPaneView.FindName("OptimizationStageText");
    private ProgressBar OptimizationProgressBar => (ProgressBar)OwnedOptimizerPaneView.FindName("OptimizationProgressBar");
    private TextBlock OptimizationProgressDetail => (TextBlock)OwnedOptimizerPaneView.FindName("OptimizationProgressDetail");
    private CheckBox ProveOptimalCheckBox => (CheckBox)OwnedOptimizerPaneView.FindName("ProveOptimalCheckBox");
    private CheckBox NewProofCheckpointCheckBox => (CheckBox)OwnedOptimizerPaneView.FindName("NewProofCheckpointCheckBox");
    private Button OptimizeDeckButton => (Button)OwnedOptimizerPaneView.FindName("OptimizeDeckButton");
    private Button PauseOptimizationButton => (Button)OwnedOptimizerPaneView.FindName("PauseOptimizationButton");
    private Button StopOptimizationButton => (Button)OwnedOptimizerPaneView.FindName("StopOptimizationButton");
    private Button VerifyOptimizationButton => (Button)OwnedOptimizerPaneView.FindName("VerifyOptimizationButton");
    private TextBlock OptimizationStatus => (TextBlock)OwnedOptimizerPaneView.FindName("OptimizationStatus");
    private Grid OptimizerBody => (Grid)OwnedOptimizerPaneView.FindName("OptimizerBody");
    private RowDefinition OptimizerOwnedRow => (RowDefinition)OwnedOptimizerPaneView.FindName("OptimizerOwnedRow");
    private RowDefinition OptimizerResultRow => (RowDefinition)OwnedOptimizerPaneView.FindName("OptimizerResultRow");
    private ColumnDefinition OptimizerOwnedColumn => (ColumnDefinition)OwnedOptimizerPaneView.FindName("OptimizerOwnedColumn");
    private ColumnDefinition OptimizerResultColumn => (ColumnDefinition)OwnedOptimizerPaneView.FindName("OptimizerResultColumn");
    private GroupBox OptimizerOwnedPane => (GroupBox)OwnedOptimizerPaneView.FindName("OptimizerOwnedPane");
    private TextBox OwnedSearchBox => (TextBox)OwnedOptimizerPaneView.FindName("OwnedSearchBox");
    private ComboBox OwnedTypeFilterCombo => (ComboBox)OwnedOptimizerPaneView.FindName("OwnedTypeFilterCombo");
    private ComboBox OwnedSortCombo => (ComboBox)OwnedOptimizerPaneView.FindName("OwnedSortCombo");
    private StackPanel OwnedAddPickerPanel => (StackPanel)OwnedOptimizerPaneView.FindName("OwnedAddPickerPanel");
    private TextBlock OwnedCollectionCount => (TextBlock)OwnedOptimizerPaneView.FindName("OwnedCollectionCount");
    private ListBox OwnedCardsGallery => (ListBox)OwnedOptimizerPaneView.FindName("OwnedCardsGallery");
    private Grid OptimizerResultPane => (Grid)OwnedOptimizerPaneView.FindName("OptimizerResultPane");
    private TextBlock Optimizer2800Metric => (TextBlock)OwnedOptimizerPaneView.FindName("Optimizer2800Metric");
    private TextBlock Optimizer2500Metric => (TextBlock)OwnedOptimizerPaneView.FindName("Optimizer2500Metric");
    private TextBlock OptimizerExpectedMetric => (TextBlock)OwnedOptimizerPaneView.FindName("OptimizerExpectedMetric");
    private TextBlock OptimizerDeadMetric => (TextBlock)OwnedOptimizerPaneView.FindName("OptimizerDeadMetric");
    private Border CampaignPlanPanel => (Border)OwnedOptimizerPaneView.FindName("CampaignPlanPanel");
    private TextBlock CampaignScopeSummary => (TextBlock)OwnedOptimizerPaneView.FindName("CampaignScopeSummary");
    private TextBlock CampaignSafetySummary => (TextBlock)OwnedOptimizerPaneView.FindName("CampaignSafetySummary");
    private TextBlock CampaignPurchaseSummary => (TextBlock)OwnedOptimizerPaneView.FindName("CampaignPurchaseSummary");
    private DataGrid OptimizedDeckGrid => (DataGrid)OwnedOptimizerPaneView.FindName("OptimizedDeckGrid");
    private DataGrid OptimizationTargetsGrid => (DataGrid)OwnedOptimizerPaneView.FindName("OptimizationTargetsGrid");
    private DataGrid LimitedCardsGrid => (DataGrid)OwnedOptimizerPaneView.FindName("LimitedCardsGrid");
    private DataGrid ExcludedCardsGrid => (DataGrid)OwnedOptimizerPaneView.FindName("ExcludedCardsGrid");
    private DataGrid PurchasePlanGrid => (DataGrid)OwnedOptimizerPaneView.FindName("PurchasePlanGrid");
    private DataGrid CampaignThreatsGrid => (DataGrid)OwnedOptimizerPaneView.FindName("CampaignThreatsGrid");
    private Button RefreshSaveButton => (Button)SaveSnapshotPaneView.FindName("RefreshSaveButton");
    private Button ApplyDeckButton => (Button)SaveSnapshotPaneView.FindName("ApplyDeckButton");
    private Button ApplyOwnedButton => (Button)SaveSnapshotPaneView.FindName("ApplyOwnedButton");
    private TextBlock SaveSnapshotStatus => (TextBlock)SaveSnapshotPaneView.FindName("SaveSnapshotStatus");
    private TextBlock SaveSourceText => (TextBlock)SaveSnapshotPaneView.FindName("SaveSourceText");
    private TextBlock SaveTimestampText => (TextBlock)SaveSnapshotPaneView.FindName("SaveTimestampText");
    private TextBlock SavePathText => (TextBlock)SaveSnapshotPaneView.FindName("SavePathText");
    private TextBlock SaveValidationText => (TextBlock)SaveSnapshotPaneView.FindName("SaveValidationText");
    private ListBox SaveDeckGrid => (ListBox)SaveSnapshotPaneView.FindName("SaveDeckGrid");
    private ListBox SaveCollectionGrid => (ListBox)SaveSnapshotPaneView.FindName("SaveCollectionGrid");
    private TextBlock LiveStatusText => (TextBlock)LiveDuelPaneView.FindName("LiveStatusText");
    private Button InspectorToggleButton => (Button)LiveDuelPaneView.FindName("InspectorToggleButton");
    private TextBlock LiveConnectionText => (TextBlock)LiveDuelPaneView.FindName("LiveConnectionText");
    private TextBlock LivePlayerLpText => (TextBlock)LiveDuelPaneView.FindName("LivePlayerLpText");
    private TextBlock LiveOpponentLpText => (TextBlock)LiveDuelPaneView.FindName("LiveOpponentLpText");
    private TextBlock LiveTerrainText => (TextBlock)LiveDuelPaneView.FindName("LiveTerrainText");
    private TextBlock LiveUpdateHealthText => (TextBlock)LiveDuelPaneView.FindName("LiveUpdateHealthText");
    private ListBox LiveHandGrid => (ListBox)LiveDuelPaneView.FindName("LiveHandGrid");
    private ListBox LivePlayerFieldGrid => (ListBox)LiveDuelPaneView.FindName("LivePlayerFieldGrid");
    private ListBox LivePlayerSpellTrapGrid => (ListBox)LiveDuelPaneView.FindName("LivePlayerSpellTrapGrid");
    private ListBox LiveOpponentFieldGrid => (ListBox)LiveDuelPaneView.FindName("LiveOpponentFieldGrid");
    private TextBlock LiveAdviceSummary => (TextBlock)LiveDuelPaneView.FindName("LiveAdviceSummary");
    private DataGrid LiveAdviceGrid => (DataGrid)LiveDuelPaneView.FindName("LiveAdviceGrid");
    private DataGrid LiveDeckGrid => (DataGrid)LiveDuelPaneView.FindName("LiveDeckGrid");
    private DataGrid LiveCollectionGrid => (DataGrid)LiveDuelPaneView.FindName("LiveCollectionGrid");
    private WrapPanel DeckPickerPanel => (WrapPanel)DeckAnalyzerPaneView.FindName("DeckPickerPanel");
    private Button AnalyzeDeckButton => (Button)DeckAnalyzerPaneView.FindName("AnalyzeDeckButton");
    private Button LoadCurrentDeckButton => (Button)DeckAnalyzerPaneView.FindName("LoadCurrentDeckButton");
    private Button CancelDeckButton => (Button)DeckAnalyzerPaneView.FindName("CancelDeckButton");
    private CheckBox DeckIncludeGlitchesCheckBox => (CheckBox)DeckAnalyzerPaneView.FindName("DeckIncludeGlitchesCheckBox");
    private TextBlock AnyFusionMetric => (TextBlock)DeckAnalyzerPaneView.FindName("AnyFusionMetric");
    private TextBlock AtLeast2500Metric => (TextBlock)DeckAnalyzerPaneView.FindName("AtLeast2500Metric");
    private TextBlock AtLeast2800Metric => (TextBlock)DeckAnalyzerPaneView.FindName("AtLeast2800Metric");
    private TextBlock AtLeast3000Metric => (TextBlock)DeckAnalyzerPaneView.FindName("AtLeast3000Metric");
    private TextBlock ExpectedAttackMetric => (TextBlock)DeckAnalyzerPaneView.FindName("ExpectedAttackMetric");
    private TextBlock DeadHandMetric => (TextBlock)DeckAnalyzerPaneView.FindName("DeadHandMetric");
    private TextBlock DeckResultSummary => (TextBlock)DeckAnalyzerPaneView.FindName("DeckResultSummary");
    private ProgressBar DeckAnalysisProgressBar => (ProgressBar)DeckAnalyzerPaneView.FindName("DeckAnalysisProgressBar");
    private DataGrid DeckResultsGrid => (DataGrid)DeckAnalyzerPaneView.FindName("DeckResultsGrid");
    private StackPanel HandPickerPanel => (StackPanel)TurnAdviserPaneView.FindName("HandPickerPanel");
    private StackPanel MonsterPickerPanel => (StackPanel)TurnAdviserPaneView.FindName("MonsterPickerPanel");
    private StackPanel SpellPickerPanel => (StackPanel)TurnAdviserPaneView.FindName("SpellPickerPanel");
    private CheckBox IncludeGlitchesCheckBox => (CheckBox)TurnAdviserPaneView.FindName("IncludeGlitchesCheckBox");
    private TextBlock TurnResultSummary => (TextBlock)TurnAdviserPaneView.FindName("TurnResultSummary");
    private DataGrid TurnResultsGrid => (DataGrid)TurnAdviserPaneView.FindName("TurnResultsGrid");
}
