"""Generate checked-in navigation and portable HTML; never fetch external content."""
from __future__ import annotations

import base64
import html
import os
from pathlib import Path
import re
import subprocess
import sys
from urllib.parse import unquote, urlsplit
import xml.etree.ElementTree as ET

import markdown

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
OUTPUT = ROOT / "output/docs"
VERSION = ET.parse(ROOT / "src/YfmCompanion.Desktop/YfmCompanion.Desktop.csproj").findtext("PropertyGroup/Version")
REMOTE = f"https://github.com/vincevandriel/yfm-fusion-companion/blob/v{VERSION}/"
CSS = """
:root{color-scheme:light}body{margin:0;background:#f3f6f8;color:#162b39;font:17px/1.65 system-ui,sans-serif}
header{background:#102636;color:white;padding:18px max(24px,calc((100vw - 1100px)/2));border-bottom:4px solid #b98524}
header a{color:#9eeaff;margin-right:18px}main{max-width:1100px;margin:32px auto;padding:20px 36px;background:white}
h1,h2,h3{line-height:1.2;scroll-margin-top:24px}h1{font-size:2.25rem}h2{border-bottom:1px solid #cbd7dd;padding-bottom:12px;margin-top:2.5em}
a{color:#006a8a;text-underline-offset:3px}a:hover{color:#944914}code{background:#edf3f6;border-radius:3px;padding:2px 4px;font-size:.88em;overflow-wrap:anywhere}
pre{background:#102636;color:#f1f5f7;overflow:auto;padding:18px}pre code{background:none;color:inherit}
table{border-collapse:collapse;width:100%;font-size:.93em}th,td{border:1px solid #cbd7dd;padding:9px 12px;text-align:left;vertical-align:top;overflow-wrap:anywhere}
th{background:#e8f1f6}tr:nth-child(even){background:#f8fafb}img{max-width:100%}.toc{background:#f0f5f8;padding:14px 24px}
footer{color:#536776;font-size:.85em;margin-top:40px;border-top:1px solid #ddd;padding-top:15px}
@media(max-width:760px){main{margin:0;padding:20px}table{display:block;overflow:auto}h1{font-size:1.8rem}}
@media print{body,main{background:white}header{background:white;color:black}a{color:black}pre{white-space:pre-wrap}h2{break-after:avoid}tr{break-inside:avoid}}
"""


def source_index() -> None:
    lines = ["# Source code index", "", "Generated by `tools/Build-Documentation.py`. Every production C#/XAML file is listed below. Declaration and named-control entries are a navigational text index, not a compiler symbol API; multiline signatures and generated members may require opening the surrounding source. Line links target the release version. Use browser Find to locate a symbol.", "", "<!-- TOC -->", ""]
    declarations = re.compile(r"^\s*(?:\[[^\]]+\]\s*)?(?:(?:public|internal|private|protected)\s+)(?!set\b|get\b|init\b).+")
    count = 0
    for project in sorted((ROOT / "src").iterdir()):
        if not project.is_dir():
            continue
        lines.extend([f"## {project.name}", ""])
        for path in sorted(project.rglob("*")):
            if path.suffix not in (".cs", ".xaml") or {"obj", "bin"}.intersection(path.parts):
                continue
            count += 1
            rel = path.relative_to(ROOT).as_posix()
            lines.extend([f"### {path.relative_to(project).as_posix()}", "", f"[Open source]({REMOTE}{rel})", "", "| Line | Declaration or named control |", "|---|---|"])
            entries = 0
            for number, line in enumerate(path.read_text(encoding="utf-8-sig").splitlines(), 1):
                if declarations.match(line) or (path.suffix == ".xaml" and re.search(r'(?:x:Name|x:Class|Click|SelectionChanged|TextChanged)="', line)):
                    summary = re.sub(r"\s+", " ", line.strip()).replace("|", "&#124;").replace("`", "&#96;")
                    lines.append(f"| [{number}]({REMOTE}{rel}#L{number}) | `{summary}` |")
                    entries += 1
            if not entries:
                lines.append("| 1 | Assembly metadata, imports or application resource declarations; open the file above. |")
            lines.append("")
    lines.extend(["## Tests and tools", "", "Tests are organized by behavior; tools have explicit entry points and are included in the solution when they are .NET projects.", "", "| File | Source |", "|---|---|"])
    for folder in (ROOT / "tests", ROOT / "tools"):
        for path in sorted(folder.rglob("*")):
            if path.suffix not in (".cs", ".ps1", ".py", ".cjs") or {"obj", "bin"}.intersection(path.parts):
                continue
            rel = path.relative_to(ROOT).as_posix()
            lines.append(f"| `{rel}` | [Open]({REMOTE}{rel}) |")
    destination = DOCS / "reference/SOURCE_INDEX.md"
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Source index: {count} production files")


def with_toc(path: Path) -> None:
    text = path.read_text(encoding="utf-8-sig")
    marker = r"<!-- TOC -->.*?<!-- /TOC -->"
    if "<!-- /TOC -->" in text:
        text = re.sub(marker, "<!-- TOC -->", text, flags=re.S)
    if "<!-- TOC -->" not in text:
        return
    converter = markdown.Markdown(extensions=["toc", "fenced_code", "tables"])
    converter.convert(text)
    entries = []
    def visit(items: list[dict]) -> None:
        for item in items:
            if item["level"] in (2, 3):
                indent = "  " * (item["level"] - 2)
                entries.append(f'{indent}- [{html.unescape(item["name"])}](#{item["id"]})')
            visit(item["children"])
    visit(converter.toc_tokens)
    text = text.replace("<!-- TOC -->", "<!-- TOC -->\n\n" + "\n".join(entries) + "\n\n<!-- /TOC -->")
    path.write_text(text, encoding="utf-8")


def main() -> None:
    source_index()
    for path in (DOCS / "DESIGN.md", DOCS / "USER_GUIDE.md", DOCS / "reference/SOURCE_INDEX.md"):
        with_toc(path)
    sources = sorted(p for p in DOCS.rglob("*.md") if "history" not in p.relative_to(DOCS).parts)
    sources += [ROOT / "README.md", ROOT / "CONTRIBUTING.md", ROOT / "THIRD_PARTY_NOTICES.md"]
    mapping = {p.resolve(): OUTPUT / (p.relative_to(DOCS) if p.is_relative_to(DOCS) else Path(p.name)).with_suffix(".html") for p in sources}
    broken = []
    for path, output in mapping.items():
        text = path.read_text(encoding="utf-8-sig")
        body = markdown.markdown(text, extensions=["toc", "tables", "fenced_code", "sane_lists"])
        def rewrite(match: re.Match) -> str:
            attr, value = match.group(1), html.unescape(match.group(2))
            parsed = urlsplit(value)
            if parsed.scheme or value.startswith("#"):
                return match.group(0)
            target = (path.parent / unquote(parsed.path)).resolve()
            if not target.exists():
                broken.append(f"{path.relative_to(ROOT)} -> {value}")
                return match.group(0)
            if attr == "src" and target.suffix.lower() in (".png", ".jpg", ".svg"):
                mime = {".png": "image/png", ".jpg": "image/jpeg", ".svg": "image/svg+xml"}[target.suffix.lower()]
                value = f"data:{mime};base64," + base64.b64encode(target.read_bytes()).decode("ascii")
            elif target in mapping:
                value = Path(os.path.relpath(mapping[target], output.parent)).as_posix()
            else:
                value = REMOTE + target.relative_to(ROOT).as_posix()
            if parsed.fragment:
                value += "#" + parsed.fragment
            return f'{attr}="{html.escape(value, quote=True)}"'
        body = re.sub(r'(href|src)="([^"]*)"', rewrite, body)
        heading = re.search(r"^# (.+)$", text, re.M)
        title = html.escape(heading.group(1) if heading else path.stem)
        def nav(name: str) -> str:
            return Path(os.path.relpath(OUTPUT / name, output.parent)).as_posix()
        page = f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><style>{CSS}</style></head><body><header>YFM Fusion Companion {VERSION}<br><a href="{nav("USER_GUIDE.html")}">User guide</a><a href="{nav("DESIGN.html")}">Design guide</a><a href="{nav("reference/SOURCE_INDEX.html")}">Source index</a></header><main>{body}<footer>Offline document. Use Ctrl+F to find text. Code and external-source links require internet access. Source revision: v{VERSION}.</footer></main></body></html>'
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(page, encoding="utf-8")
    if broken:
        raise ValueError("Broken local documentation links:\n" + "\n".join(broken))
    subprocess.run([sys.executable, str(ROOT / "tools/CreateUserGuide.py")], cwd=ROOT, check=True)
    print(f"Validated and rendered {len(mapping)} offline HTML documents and the illustrated PDF.")


if __name__ == "__main__":
    main()
